### ISSUE TITLE
Set up code coverage

### ISSUE THREAD

**Issue by lencioni** [Galooshi/import-js#169]
We recently fixed a bug in goto that would have been caught earlier if we had a test covering it. I think that setting up some code coverage reports would be helpful for us to make this project more resilient by alerting us to gaps that we might want to fill.

**Comment by lencioni** [comment]
Looks like coverage with Jest in November 2015 was pretty flaky: https://github.com/facebook/jest/issues/595

**Comment by rhettlivingston** [comment]
I've been quiet for a couple of days because I've started using node-inspector to debug instead of hacking with console statements. I immediately started noting things that made me think a) I don't know the general theory of operation for the code well enough and b) there are things going wrong we're not aware of.

One of the things that threw me is the following line [found here in jsModule](https://github.com/Galooshi/import-js/blob/master/lib/JsModule.js#L158) I encountered while stepping through. "startsWith" didn't look at all right.
```js
      if (!this.filePath.startsWith('/package.json')) {
```
I found that it has been in the code since the conversion to JavaScript. [Before conversion](https://github.com/Galooshi/import-js/blob/0635ef3a17ccc985e707117f6ab753fdbf90573c/lib/import_js/js_module.rb#L145) it was
```
        return @file_path unless @file_path.end_with?('/package.json')
```
so it's definitely wrong.

I cut my coding teeth on the integration test equipment development side of military avionics development (AV-8B and F/A-18) and have thus been trained to immediately ask "how did this happen". The first thought was, of course, that something isn't being tested.

I turned on Jest coverage, examined the generated html report, and very quickly saw that all tests return at this point because the path never starts with /package.json. So the code after that isn't covered. I've also noted bad coverage in the meteor environment code. I knew that I wasn't getting the failure and unusual path cases covered, but seeing it spurs you on. 

Whether or not we continuously integrate coverage, we need to be using it ourselves.

**Comment by lencioni** [comment]
Agreed. I'll look into setting up code climate for this project.

**Comment by trotzig** [comment]
That's a great find. I have a vague memory about that particular line. I think I first converted it to `endsWith` only to realize there was no such method. So I then made it an `indexOf` only to later (incorrectly) switch to `startsWith`. I'm glad we're doing this.

**Comment by rhettlivingston** [comment]
You were just waiting for endsWith to appear - 5 character fix now. :smile:
