### ISSUE TITLE
Complete import/require from partial `import`/`require`

### ISSUE THREAD

**Issue by ljharb** [Galooshi/import-js#217]
I'd love to be able to do: `import foo` or `import foo from` or `var/const/let foo = require` and hit a command to have it complete the import, _without_ having any code yet present to use it. The typical flow for most devs is to think about imports/requires first, before any code is typed :-)

(filed per @lencioni)

**Comment by lencioni** [comment]
I think it might make sense and work well to expand our current import
command for this type of use case. If we pass the line and cursor position
to import js from the editor instead of just the current word, we could
fall back to this type of behavior after failing to fix the word.

I think that would be pretty slick and would be a nice stepping stone as
developers learn to stop thinking about their imports.

**Comment by lencioni** [comment]
How should this behave in regards to grouping and sorting imports?

**Comment by ljharb** [comment]
It should complete them all, then group them all, then leave my cursor either a) at the bottom or b) on the one it just completed (probably b).

Similarly, pretty much any import-js command should probably complete the import since it's syntactically invalid otherwise.

**Comment by trotzig** [comment]
Interesting, I haven't really thought about such a workflow. I've done something similar from time to time, when I just type a few words and import them one by one. E.g.

```js
React Proptypes 
```
place cursor on "React", and import that word:

```js
import React from 'react';

React PropTypes
```

place cursor on "PropTypes" and import it:

```js
import React, { PropTypes } from 'react';

React PropTypes
```

Then delete the words:
```js
import React, { PropTypes } from 'react';

```

I wonder if this is enough for you? It's probably easy to write a Sublime plugin that wraps those steps so that you can select a few words, import them using import-js, then delete them. And if that works well, we can integrate it into import-js by default.

**Comment by ljharb** [comment]
I'm not sure that would be enough (even though it certainly "works") - the idea is that I want to have import-js shorten the normal, common workflow one uses when *not* using import-js - not that import-js would alter my workflow *in any way* besides speeding it up.

**Comment by trotzig** [comment]
I understand. If you have an idea for how to implement it, I'm happy to accept a PR or a more detailed spec.

**Comment by vini175pa** [comment]
@ljharb Give a look at this plugin https://github.com/vini175pa/sublime-simple-import. Currently it's only available for Sublime, but if it satisfies what you need, I can integrate it on `import-js`.

It's a "import creator". I doesn't matter if you have a module installed or not, it will only create the import ( or require ), but it will look on the project's file to create a relative path.

**Comment by trotzig** [comment]
We could add support for this by allowing fix_imports to scan the file for incomplete imports and expand them inline. That would help the usecase described in #238 as well. There's a bit of parsing to implement, and we need to keep track of where (line and column number) the incomplete import is located, but is should be doable.

**Comment by trotzig** [comment]
I'm going to close this. The direction I ended up taking in 2.1 (using babylon to parse the file) makes anything that isn't valid javascript hard to work with. This feature is still be possible to implement, but I don't think it fits into the tool at this point.

**Comment by ljharb** [comment]
Makes sense, but imo it makes the tool much less useful :-/
