### ISSUE TITLE
Convert to JavaScript

### ISSUE THREAD

**Issue by lencioni** [Galooshi/import-js#221]
- [x] Rewrite the importer test (importer_spec.rb) to use the command line tool
- [x] Rewrite the vim plugin to instead use the command line tool
- [x] Update atom plugin
- [ ] Rewrite emacs plugin to use command line tool
- [x] Start a new Node project and port code over, starting with the importer test
- [x] Add features one by one
- [x] Move all plugins over to the new project

---

I've been considering this for a while now, but I think I've recently been pushed over to the side of we should convert import-js to JavaScript. I'm opening this issue to discuss the idea and if we agree then come up with a plan.

Advantages:

- Easier to install (#17, #219, #220)
- More useful in environments used by people writing JavaScript (#218)
- Likely much faster when fixing imports by ditching ESLint dependency (#202)
- Likely able to unlock more powerful and accurate transformations via JS AST tools
- Level the playing field for editor integrations by making the command line tool the only interface
- Likely easier for JavaScript developers to contribute

Disadvantages/risks:

- Time and effort to rewrite
- Possibility of introducing bugs
- Possibility of pushing out work that might be higher priority

**Comment by trotzig** [comment]
This definitely makes sense to me. This project has evolved steadily since it's modest introduction as a vim plugin in November 2014. 

Making it a standalone command-line tool is a good idea. The vim plugin should then become a little simpler. The Sublime plugin might not have to change at all. But the Emacs plugin will have to be rewritten a little. 

I think this project has reached a level of maturity that allows us to halt execution a bit. There are no big issues open, and the work we've done in the last couple of months have been less about the core, and more about polish. 

In terms of sequencing, how does this sound for a plan?

1. Rewrite the importer test (importer_spec.rb) to use the command line tool
2. Rewrite the vim plugin to instead use the command line tool
3. Rewrite emacs plugin to use command line tool
4. Start a new Node project and port code over, starting with the importer test
5. Add features one by one
6. When done, move all plugins over to the new project

The good thing about this is that we can keep fixing bugs here while working on the new thing. We can also add plugins for other editors as long as we use the CLI tool. 

We're in crunch mode at work right now, so for me it probably won't work to start right away. And I'm still on part-time parental leave. Though that will end in a few weeks, and then I'll have a few more cycles available. How about you @lencioni?

**Comment by trotzig** [comment]
Should we do this under the diffux umbrella btw? It's sort of our common identity. :)

**Comment by lencioni** [comment]
I think what you outlined sounds like a good plan. I'd like to get the atom plugin before starting on this, but that doesn't really change anything.

As for rewriting the importer test, I was thinking it might be interesting to abstract the tests into some sort of data structure that expresses what the file looks like before running, what the file looks like after running, configuration, and arguments to the command line tool. With this approach we could first extract the tests and then change the test runner at any time while touching minimal code. This is a pattern that I've seen used by projects like [ESLint](https://github.com/eslint/eslint/blob/master/tests/lib/rules/accessor-pairs.js) (JS object-based) and [Babel](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-es2015-arrow-functions/test) (fixture-based). For this case, I think I prefer the fixture approach since we are operating on entire files. What do you think?

As for time, I'll probably keep cranking away at roughly the same pace as I have been.

> Should we do this under the diffux umbrella btw? It's sort of our common identity. :)

I think it makes sense to move this to an organization, and I think it would be fine to move diffux there as well, but I don't think we should move this into the diffux organization.

**Comment by lencioni** [comment]
I updated the original issue with a checklist of tasks from your comment @trotzig.

**Comment by trotzig** [comment]
Very minor detail, but still: let's avoid shrinkwrapping! It's been the source of a lot of frustration for me lately (seemingly random changes, often fails, inconsistent flattening, etc.).

**Comment by lencioni** [comment]
I don't think we'll need shrinkwrap for this use case.

As for your frustrations, perhaps there is a shrinkwrap tool that could help you? (Like this one maybe? https://github.com/uber/npm-shrinkwrap)

**Comment by trotzig** [comment]
yeah, used that for a while, but it wasn't compatible with a newer version of npm (or node, can't remember). So we went back to plain shrinkwrapping. Another pain I felt was that a full `npm install` after removing the node_modules folder (which you have to do from time to time) would take forever on a VPN (we use an internal npm registry).

**Comment by lencioni** [comment]
Linking this conversation about the CLI API here to prevent it from getting lost: https://github.com/trotzig/import-js/commit/69e888164a42c31e2c77bf3cf75f0ec2d414adfe#commitcomment-16526005

**Comment by trotzig** [comment]
I started working on rewriting the importer_spec here: https://github.com/trotzig/import-js/commits/rewrite-spec

My plan is to first make it use the CommandLineEditor, then look at ways to generalize even further (like eslint and babel does).

**Comment by lencioni** [comment]
Cool! When we start actually writing JS, we should probably decide on a testing framework. I've been using mocha, chai, and sinon at work which is pretty similar to jasmine, but a tiny bit better because the pieces are individually composable instead of being all bundled together.

I know that Jest has been getting some love recently, and some people seem to really like Tape. Ava might also be worth looking at.

**Comment by ljharb** [comment]
+1 for tape!

**Comment by trotzig** [comment]
Thanks for making me aware of all those projects @lencioni!

I was going to suggest Jest, mainly because
- it uses Jasmine assertions (which I'm most familiar with)
- I can see a (somewhat) quick port of the current rspec suite to Jest
- It has extensive [documentation](https://facebook.github.io/jest/)

But I don't have a super strong opinion. If someone other than me gets started on it, feel free to pick whatever you think fits.

**Comment by trotzig** [comment]
@ljharb can you try to convince me into using tape? I'm interested to know why you +1'ed it!

**Comment by ljharb** [comment]
@trotzig I'm not a fan of BDD style assertions. mocha (and jasmine, iirc) rely on globals and thus need a custom runner (i might be wrong on jasmine tho, haven't used it in awhile). jest is new, but all i've heard about it is problems with mocking things when trying to use other libs. tape is simple assertions, relying on the way JS works, without any magic.

**Comment by trotzig** [comment]
I see, thanks for explaining! I myself don't have a problem with BDD style assertions, but I might just be blinded by how I've been doing things for a while.

**Comment by trotzig** [comment]
I got too excited about porting this, so I started working on a branch: 

https://github.com/trotzig/import-js/tree/convert-to-js

Feel free to work on that branch too. If you do, make sure to drop a line here when you start. So that we don't end up doing duplicate work.

**Comment by lencioni** [comment]
Although we haven't updated the emacs plugin yet, we plan on doing that soon. I'm going to close this out as finished! Good work.
