### ISSUE TITLE
Gets tripped up by imports that don't assign to variables

### ISSUE THREAD

**Issue by lencioni** [Galooshi/import-js#230]
I have seen the following code:

```js
import './foo';
```

which import-js doesn't think is an import statement, causing problems with things like sorting and grouping.

**Comment by trotzig** [comment]
Yeah, we have that too in the Brigade codebase. 

```
require('./index.scss');
```

Where do you suggest we put it? In what group I mean.

**Comment by lencioni** [comment]
The groups are all based on paths, so it can use the same logic as other import statements.

**Comment by lencioni** [comment]
Actually, I think these should go in their own group at the very top, and maybe not sorted alphabetically, since they are used for side effects that other imported things may depend on.

**Comment by trotzig** [comment]
I see, though it might be that they introduce side-effects not wanted by some imports.

**Comment by rhettlivingston** [comment]
@trotzig, are you planning on working this one? If not, I'd like to tackle it. Just making sure I'm not duplicating effort.

**Comment by trotzig** [comment]
Nope, I wasn't planning on doing so. Go ahead!

**Comment by lencioni** [comment]
@rhettlivingston You've made good contributions to this project, so I've added you as a collaborator! We prefer to send most changes through PRs so that they can be code reviewed by others before hitting master. Welcome aboard!

**Comment by rhettlivingston** [comment]
Thank you! I greatly appreciate the vote of confidence!

Keeping a fork with multiple branches up to date with the main project that sometimes has branches I'd like to use in my branches has been,,, educating. :smile:

**Comment by rhettlivingston** [comment]
I got the bulk of the change implemented, or so I thought. "fix" tolerates the statements and passes them through. I haven't yet sorted them to the top. All tests are passing.

In testing it, I was using a test case in which I had removed some imports beyond those statements, but not all. I noticed that the imports that I had left in the file were being picked up and put in the right groups but passed through verbatim instead of having their filenames corrected per the current setting of useRelativePaths.

So I reread the README and noted the "rewrite" command which I've never tried. It was fortuitous because, despite all tests passing, my changes had broken it severely. It was throwing an exception and accomplishing nothing. It isn't ready to handle situations in which a module had no variables associated with it. I'm working on it.

But, this brings up a question. "fix" is not doing everything I had instinctively expected it to do. Only a "fix" followed by a "rewrite" can achieve a full correction of the imports specifications to match all of the desires expressed by my settings. Is this by design, or is fix falling short of its mark?

**Comment by trotzig** [comment]
Historically, the main reason for keeping those commands separate is that`rewrite` wasn't stable enough to replace `fix`. `rewrite` was added later on as a tool to batch-update imports for an entire app. In my opinion, and when run on the codebase I mostly hack on (brigade), it is too aggressive -- breaking imports that had been constructed manually. For instance, we have stuff like this:

```js
const ProfileRoutes = require('bundle?lazy!routes/ProfileRoutes');
```

(The `bundle?lazy!` part will cause the assigned variable to be a function that on invocation will download the module lazily)

**Comment by rhettlivingston** [comment]
> In my opinion, and when run on the codebase I mostly hack on (brigade), it is too aggressive

I had that opinion as soon as I saw its implementation.

However, I was led to find rewrite by something in fix that didn't seem aggressive enough. If a filename can be easily resolved, I'd expect fix to cause it to conform to the current setting of useRelativePaths. If not (as would be the case in your example above), sure, just pass the filename through. At a lesser level, I'd also expect it to force line lengths to obey maxLineLength, and I'd like to see an option to never output more than one named import on a line as that is a common formatting standard.

I'm not thinking that rewrite is a great routine. It seems to me it should never be necessary. I think "fix" can be incrementally improved to more completely accomplish what the user has specified in their settings without breaking the special cases.

**Comment by trotzig** [comment]
I like the idea of incrementally making it better. Is there anything I could do in the immediate future that would help the changes you are making?

**Comment by rhettlivingston** [comment]
I just pushed my current work to a "support-side-effect-imports" branch. If you could go ahead and add support in Configuration for the moduleSideEffectImports spoken of in 295, I could put in the appropriate call to make use of it. No super hurry because I've got a couple issues left in this + testing + I'm simultaneously investigating how to extract exports from code. So I won't be twiddling my thumbs :smile:

**Comment by trotzig** [comment]
Will do! I hope to push something soonish, because I need to attend something different in ~30 mins.

**Comment by trotzig** [comment]
I pushed something to the `moduleSideEffectImports` branch. It's not completely done, but almost. I want to flesh out the tests a little, add a message (something like `added 2 side-effect imports` and update the README.

**Comment by rhettlivingston** [comment]
Great! I made a comment on a probably obscure but confusing if it occurs gotcha that I suspect we've missed.
