### ISSUE TITLE
ImportJS should be able to run as a subprocess

### ISSUE THREAD

**Issue by kevinkehl** [Galooshi/import-js#261]
In the transition to 0.7.0, we lost the ability for importjs to run as an editor subprocess. This means that every importjs command needs to spin up a new node process. At least for the Emacs plugin, this significantly increased the perceived lag of performing an import.

The nodejs version should be updated to run as a process, listening for input from stdin and writing JSON to stdout.

**Comment by trotzig** [comment]
Should we have this as a separate command perhaps?

**Comment by lencioni** [comment]
I think it should either be a separate command, or what happens when you run `importjs` without any arguments.

**Comment by lencioni** [comment]
I wonder how much time is spent shelling out vs. importjs startup time. We might be able to get big enough wins by simply opening an interactive shell and interacting with importjs as you would normally on the CLI. We might as well start here since nearly all of the work would be necessary to try out the solution proposed here anyway.

**Comment by trotzig** [comment]
Related to this issue, I've started working on using watchman to keep an updated index, and by doing so speeding up the file-finding process significantly. It would be interesting if you could try it out! https://github.com/Galooshi/import-js/tree/watchman

**Comment by trotzig** [comment]
There's now the `importjsd` command you can use.
