### ISSUE TITLE
Path with backslashes on Windows

### ISSUE THREAD

**Issue by moranda** [Galooshi/import-js#351]
On windows (at least with atom), path is written with backslashes, which is quite problematic since they are considered as escape characters in the javascript code. They should be automatically replaced with slashes.

**Comment by trotzig** [comment]
I'm being lazy here, as I could try to get access to a windows machine to try things out. But would you be able to try out the latest version of the tool to see if the same issue exists @moranda? Most of the path-handling code in import-js has been rewritten, and it's possible that this issue has been magically fixed somehow.

**Comment by rndmerle** [comment]
Hello.
Still getting backslashes on Windows, using atom-import-js 0.7.0
For instance, I'm getting :

`import { uiSelectors } from '..\Redux\uiRedux';`

**Comment by trotzig** [comment]
Ouch, that's not great. Windows support is something that we've found hard to maintain since the main contributors are all users of either mac or linux. We'll make spikes to fix certain issues (like https://github.com/Galooshi/import-js/pull/401), but then we don't have time to follow up on other changes. Sorry about that.

Fixing this bug is likely not too complicated. A naive solution I could think of is to alter the `pathToImportedModule` variable here, replacing back slashes to forward slashes: 
https://github.com/Galooshi/import-js/blob/a4a284ba5ab710f5fa7eca5b9425214d2d3f813a/lib/JsModule.js#L168

If anyone seeing this thread feels up to the task, I'd be thrilled. I'll provide as much guidance as you need along the way.

**Comment by rndmerle** [comment]
Wait, it's actually my fault.
On my project I've a second package.json further down the tree (in app/) and in fucks everything up, including the slashes. Going to Issue that bug a bit later.

**Comment by rndmerle** [comment]
Wait, it's actually my fault.
On my project I've a second package.json further down the tree (in app/) and it fucks everything up, including the slashes. Going to Issue that bug a bit later.

Slashes are working fine on Windows. Sorry for the troubles.

**Comment by rndmerle** [comment]
Ok actually it's half-good.

`useRelativePaths: false,`
gives
`import { uiSelectors } from 'app/Redux/uiRedux';`

and 
`useRelativePaths: true,`
gives
`import { uiSelectors } from '..\Redux\uiRedux';`

**Comment by trotzig** [comment]
Ah, good catch! That means that it's probably isolated to this this bit of code that uses `path.relative` to find the relative path to use in the import statement: 
https://github.com/Galooshi/import-js/blob/a4a284ba5ab710f5fa7eca5b9425214d2d3f813a/lib/JsModule.js#L104

**Comment by rndmerle** [comment]
I'll work on a PR tomorrow. Actually there is a good amount of changes to pass all the failed tests on Windows.

**Comment by lencioni** [comment]
I think this was fixed in 2.4.0. Please re-open if you are still having problems!
