### ISSUE TITLE
2.1-beta.2: Ambiguous CommonJS default export scenario

### ISSUE THREAD

**Issue by dcporter** [Galooshi/import-js#361]
A common pattern for developers exporting multiple things from a CommonJS module who don’t want to type `module.exports.` a bunch is to replace the exports object with a plain object of their own, with all of the things they want to export. (See example code below.) In v2.1.0-beta.2, `findExports` thinks that this scenario results in both named exports and a default export, but this was not the developer’s intention, and expands the space for the generation of false imports.

I propose that this kind of export — a plain JavaScript object with members — be considered a non-default export. Specifically, if the ExpressionStatement’s expression is an assignment and its left side is "module.exports" and the right-hand side is an ObjectExpression whose `properties.length` is greater than zero.

```js
function localFunction1() {}
function localFunction2() {}

module.exports = {
    localFunction1,
    localFunction2
};
```

**Comment by trotzig** [comment]
Theoretically, I think this makes sense. But I worry that it will confuse people more than it helps. For instance, we have a few "singleton" object exports in our code. Things like:

```js
// foo.js
module.exports = {
  init: function()  { ... },
  stop: function() { ... },
};
```

I usually don't want to import `init` directly, because of the over-general name. So we import the entire object, and then call methods on it. 

We're trying to take an es6-first approach to our development of this tool, and I think this is just one of the quirks you'll have to live with if you use common-js. Agree? 😃

**Comment by dcporter** [comment]
Very agree!

**Comment by trotzig** [comment]
I appreciate the feedback here, it's good to get the named exports code battle-tested before we release it.
