### ISSUE TITLE
Command line: Dependencies aren't re-indexed after npm update.

### ISSUE THREAD

**Issue by dcporter** [Galooshi/import-js#376]
When `node_modules` dependency is updated, and the command line utility subsequently run, `ExportsStorage#needsUpdate` fails to flag the dependency's main file as needing to be reindexed, so new exports aren't found.

The root cause appears to be that `needsUpdate` is receiving the wrong `mtime` from `ModuleFinder`: when ModuleFinder expands files (in `expandFiles`), it flags each dependency file with the `mtime` of the *root package.json*, [here](https://github.com/Galooshi/import-js/blob/master/lib/ModuleFinder.js#L44). It should instead go get the `mtime` of the *dependency's main file*. (That whole stack is already super asynchronous, so at least it shouldn't take any external rearchitecting to fix.)

Edit: added link to [the root cause](https://github.com/Galooshi/import-js/blob/master/lib/ModuleFinder.js#L44).

**Comment by trotzig** [comment]
Good catch! I'll try to find time for a fix soon. If you want to take a stab at it, I'd be happy to accept a PR. You're right in that we need to check for a different `mtime`. There's a `lastUpdate` module that we can use to get the right timestamp.

**Comment by trotzig** [comment]
I made a quick stab at fixing this (on [the reindex-node-modules branch](https://github.com/Galooshi/import-js/tree/reindex-node-modules)), but I realize it's a little bit trickier than simply using the right `mtime`. I made a decision earlier to not watch the `node_modules` folder for changes, and instead just trigger updating exports from package dependencies on changes to `package.json`. This is good for performance, since `node_modules` can get quite large. But it makes the cache stale when you update dependencies without touching `package.json`. 

I'll try to come up with a solution that doesn't involve having to watch node_modules for changes. If you have any ideas on that, let me know!

**Comment by dcporter** [comment]
First off, ran that branch locally and confirmed that it works great from the command line. It's only mid-daemon that it falls down. I'm currently working on the command line, so this solves some pain for me personally right out of the gate (🎉😄 thanks!).

> I'll try to come up with a solution that doesn't involve having to watch node_modules for changes. If you have any ideas on that, let me know!

I do have some best-tradeoffs thoughts, I'll write them up and post them here, hopefully today.

**Comment by dcporter** [comment]
I'm splitting this issue in two; since your branch has solved the command-line use case, I'm focusing this on that, and opening a new one for the daemon side of things. I'll post my watching-dependencies thoughts over there.

Thanks again for the fix, it works and it looks good to send to master?

**Comment by trotzig** [comment]
I need to clean up a few things before merging, but I agree that this makes things slightly better.

**Comment by dcporter** [comment]
Fixed in 50a9fa
