### ISSUE TITLE
Named and default export with the same name

### ISSUE THREAD

**Issue by rndmerle** [Galooshi/import-js#445]
_Before considering working on a PR here is a potential improvement, but not sure if it's appropriate._

When using composition, a popular pattern is to name-export the base component and to default export the composed component, and this from a file with the same name (the purpose is to easily test the base component).
```
// Component.js
export const Component = {};
export default enhance(Component);
```

Then when you want to import the component, **most of the time you need the default import**:
```
import Component from './Component';
```

but it seems the **named import has priority** as we get:
```
import { Component } from './Component';
```

It could be considered as an anti-pattern I guess but it's quite popular nevertheless. I started to export that way when using HOCs.

So, what's the right behavior? Maybe asking which one should be imported?

**Comment by coagmano** [comment]
I think there's trouble working out what the default export should be called. Officially it's name is `default` but you could keep track of the variable it was passed (if it's passed one) or use the file name?

**Comment by trotzig** [comment]
Sorry for the late input here (I've been on a long vacation). The behavior I'm seeing is that both are presented to the user, so they can decide manually. Is that not the case for you?

**Comment by rndmerle** [comment]
The idea would be to present both yea.
But again, it's just an idea because of the supposed popularity of this exporting pattern.

Currently, there is no choice, the named import is preferred, and there is no way both options to be presented to anyone because 1) one of the options is trimmed out by `dupeandsort()`, and 2) in the `unresolvedImports` array _(then  used for the choice popup on an editor add-on for instance)_, items are only differenciated by their `importPath`, there is no named/default specifier to differentiate the options.

**Comment by trotzig** [comment]
Ah, I see what the problem is now. It's definitely a design issue with how the `unresolvedImports` interaction is with the editors. We need to send more information about the choice made by the user. 

This has come up before. In the beginning we used to just send the selected index from the `unresolvedImports` array. And then on the receiving end we would replay the entire import process, with modules already resolved (through their index). That was inefficient, and could potentially lead to mismatches (if things changed between the initial import and the replay). 

Because of this, I'd propose a solution that would make some information opaque to the client. Instead of passing down the `importPath`, we'd pass down an object that we received attached to the variable to resolve imports for. In json words, instead of this: 

```json
{
  "Button": [
    { 
      "displayName": "import { Button } from './Button'",
      "importPath": "./Button"
    },
    { 
      "displayName": "import Button from './Button'",
      "importPath": "./Button"
    },
  ]
}
```

We'd send something like: 

```json
{
  "Button": [
    { 
      "displayName": "import { Button } from './Button'",
      "data": { "isNamedExport": true, "importPath": "./Button" }
    },
    { 
      "displayName": "import Button from './Button'",
      "data": { "isNamedExport": false, "importPath": "./Button" }
    },
  ]
}
```

Then the client wouldn't have to worry much about what to send down, it would just take what's in `data` and pass it along. The receiving end (importjs daemon) can then make sure that the data is enough to inject an import statement. The `data` object would most likely have to look like a serialized version of an `ImportStatement` instance.

**Comment by rndmerle** [comment]
It sounds pretty nice.

**Comment by rndmerle** [comment]
Pull request https://github.com/Galooshi/import-js/pull/451
