### ISSUE TITLE
lodash/fp problem (hacky exports)

### ISSUE THREAD

**Issue by kahless** [Galooshi/import-js#484]
There are packages that export names in a hacky way. For example "lodash/fp" exports this:

    var _ = require('./lodash.min').runInContext();
    module.exports = require('./fp/_baseConvert')(_, _);

import-js does not see this export and does not generate such imports:

    import { assoc, reduce, keys, compose, pull } from "lodash/fp";
    // import-js does not generate this!
    // No JS module to import for `...some lodash function name`

I can make a script like this to re-export functions and provide them to import-js:

    export { assoc, reduce, keys, compose, pull, ... } from "lodash/fp";

But such imports are not grouped correctly with other third party npm dependencies. "namedExports" property can be a workaround for this problem, but it is deprecated. Perhaps it should not be deprecated? Or am I missing something? I use lodash all the time so I need an automated tool for generating imports.

**Comment by trotzig** [comment]
We don't have a good way to solve this without the `namedExports` config option at the moment. Which means it's highly unlikely that we'll be able to remove the option any time soon. Keep using it, and keep reporting the cases where it doesn't work. That way we have a solid understanding of what  we need to do in order to drop support. 

https://github.com/Galooshi/import-js/issues/483#issuecomment-369397075

**Comment by kahless** [comment]
If `namedExports` — is a right solution then we should remove a deprecation warning to not confuse the others. Nobody will use this option if readme says you are about to remove it. And we should fix the code to remove this annoying warning:

    Using namedExports to configure ImportJS is deprecated and will go away in a future version.

**Comment by trotzig** [comment]
Agreed. Would you be able to take that on?

**Comment by kahless** [comment]
Yes :) I will prepare a pull request soon.
