### ISSUE TITLE
Prop-types and immutable modules

### ISSUE THREAD

**Issue by ivangeorgiew** [Galooshi/import-js#496]
Right now in order to `import { List, Map,....} from 'immutable` and `{ bool, string, func,...} from 'prop-types'` I have to use namedExports setting.

I receive a warning message that this setting will become depricated in the future.
Can you please either remove the message or make those imports work by default ?

**Comment by trotzig** [comment]
The message is already removed, it will get shipped as part of the next release. https://github.com/Galooshi/import-js/commit/8d3b2677b34ba076bc5b544bd8399258e4fe4dff

Statically detecting exports from the prop-types module is hard since the exports are dynamically generated: https://github.com/facebook/prop-types/blob/534a07a3a52d2447e2a65ebf9f7635d858682ee0/index.js

Once we have progress on https://github.com/Galooshi/import-js/issues/490, we could add an `importjs-plugin-react` module that would configure a few named exports explicitly. Until work is done there, you'll have to use `namedExports`.
